language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "bbilger-github"
    token:
      secure: $SONAR_TOKEN
env:
  global:
    - secure: "SQuzRAzkaYqAdTMnWcGRAawerGXSkW4AvXAO8yKCAbSQFnkO/ik3yXB/RBLaw0WRPXx+OpcCD7/s5ySfpYvLgMK8pLdZeZEco8Kpacsoyn3QICiexy5B5HkuW8rapBmOUHGWPrf0/lutDM6gCPEDqkQc76SRekY+foKGqa42lrlgGOeL8CxA+LeK33UoPvkK406YiJeioloRugnjA7u2eg1ISspkqlxN1N1kGfmkB4uV1J8rFg+4M6Of8YUqYvL52K8APgq06P97PfLhcUzOloC0NlFX8Tr4fibqFoiS4UIFTWqWMLdt5tyHfb2uEBP6I5fbM1PCEKg6yoRlw7HqXkTiEVHazz9Xm+Bt92vfF4f7GBfKurwHsiXHy6OXRbiZGQB//oHIDh1Z9QTR6eFVtt66Jf5+wN+AUtHwAigo8G7VOJtzpN9U5P2W68HjgLGbT72vjL+R3HWf0U3/JxgL8d9VSDQheO9iw80yzbKNIyscAdc6mbqCm1TZaTh5/TLNsCXDtUffJCSY4BUR1BkLmB8HWrr5m0JbvLa5ufJSE6UgDj1ZzjLBra5sJrx8CXwWvp9wE/M0zfAEcb5NJ0Mg1s7qcybobKjbPR3jsXkH2h3eukMbpe8Nk6BYZ03ywg6XltL3a3SLiNJIkqkw5xmboVWh0FFeGu72h3ND5e4bvbI="
script:
  - ./gradlew clean build sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
